init:
  detector: COCOA

  gpu: 0
  precision: medium
  chunk_size: 512 # 128
  batch_size: 512 # 256
  num_workers: 9

  model:

    config_path_v   : configs/cocoa/model_configs/var_mini.yml
    config_path_ms1 : configs/cocoa/model_configs/model_stage1_mini.yml
    config_path_ms2 : configs/cocoa/model_configs/model_stage2.yml
    checkpoint_path : .cometml-runs/hgpflow_v2/f7da188fde5248f68c8bf3077e8eae9a/checkpoints/epoch=40-val_total_loss=0.0508.ckpt

  ind_threshold_loose: -0.1 # 0.2
  ind_threshold_plot: 0.48
  store_seg: false

items:
  - info: "dijet val"
    run_pred: true
    run_plot: false

    seg_path: /pscratch/sd/a/agolub/split_cocoa_8000_9000.root
    truth_path: null
    pred_path: null

    dir_flag: dijet_val
    n_events: 200
